package com.google.android.gms.nearby;

import com.google.android.gms.common.Feature;

/* JADX INFO: compiled from: com.google.android.gms:play-services-nearby@@19.4.0 */
/* JADX INFO: loaded from: classes4.dex */
public final class zza {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature zzH;
    public static final Feature zza;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    static {
        new Feature("nearby_sharing", 38L, true);
        new Feature("nearby_sharing_allow_permission_auto", 1L, true);
        new Feature("nearby_sharing_get_phone_numbers", 1L, true);
        new Feature("nearby_sharing_ignore_consent", 2L, true);
        new Feature("nearby_sharing_phonesky", 6L, true);
        zza = new Feature("nearby_connections", 3L, true);
        zzb = new Feature("nearby_connections_v2", 2L, true);
        zzc = new Feature("nearby_connections_v3", 1L, true);
        zzd = new Feature("nearby_fast_pair", 4L, true);
        zze = new Feature("nearby_fast_pair_sass", 4L, true);
        zzf = new Feature("nearby_fast_pair_get_sass_device_info", 1L, true);
        zzg = new Feature("nearby_fast_pair_settings_integration", 2L, true);
        zzh = new Feature("nearby_fast_pair_trigger_fast_pair_by_account_key_at_given_address", 1L, true);
        zzi = new Feature("nearby_fast_pair_trigger_firmware_update_check", 1L, true);
        zzj = new Feature("nearby_fast_pair_update_active_tracking_method", 1L, true);
        zzk = new Feature("nearby_fast_pair_unblock_pairing", 1L, true);
        zzl = new Feature("nearby_fast_pair_set_anc_mode", 1L, true);
        zzm = new Feature("nearby_fast_pair_set_firmware_update_check_time", 1L, true);
        zzn = new Feature("nearby_fast_pair_validator", 1L, true);
        zzo = new Feature("nearby_fast_pair_wear_os", 3L, true);
        zzp = new Feature("nearby_fast_pair_wear_peripheral", 1L, true);
        zzq = new Feature("nearby_fast_pair_wear_peripheral_notify_disable", 1L, true);
        new Feature("nearby_presence", 5L, true);
        new Feature("nearby_presence_broadcast_request_api", 1L, true);
        new Feature("nearby_presence_discovery_request_api", 2L, true);
        new Feature("nearby_presence_format_medium_support", 1L, true);
        new Feature("nearby_presence_get_version", 1L, true);
        new Feature("nearby_presence_reset", 1L, true);
        new Feature("nearby_presence_sync", 1L, true);
        zzr = new Feature("nearby_connections_get_local_endpoint_id", 1L, true);
        zzs = new Feature("nearby_connections_get_local_endpoint_id_v2", 1L, true);
        zzt = new Feature("nearby_connections_register_device_provider", 2L, true);
        zzu = new Feature("nearby_connections_update_advertising_options", 2L, true);
        zzv = new Feature("nearby_connections_update_connection_options", 1L, true);
        zzw = new Feature("nearby_connections_update_discovery_options", 1L, true);
        zzx = new Feature("nearby_connections_setting", 1L, true);
        zzy = new Feature("nearby_connections_set_downloads_directory", 1L, true);
        zzz = new Feature("nearby_connections_stop_with_task", 1L, true);
        new Feature("nearby_sharing_everyone_mode", 2L, true);
        new Feature("nearby_sharing_toggle_fast_init_notification", 1L, true);
        new Feature("nearby_sharing_batch_contacts_editing_request", 1L, true);
        zzA = new Feature("nearby_uwb", 3L, true);
        zzB = new Feature("nearby_uwb_add_controlee", 2L, true);
        zzC = new Feature("nearby_uwb_remove_controlee", 2L, true);
        zzD = new Feature("nearby_uwb_get_chip_ids", 1L, true);
        new Feature("nearby_uwb_get_chip_infos", 1L, true);
        zzE = new Feature("nearby_uwb_add_controlee_with_session_params", 1L, true);
        zzF = new Feature("nearby_uwb_reconfigure_range_data_ntf", 1L, true);
        zzG = new Feature("nearby_uwb_reconfigure_ranging_interval", 1L, true);
        zzH = new Feature("nearby_uwb_get_local_address_with_chip_id", 1L, true);
        new Feature("nearby_sharing_get_device_account_id", 1L, true);
        new Feature("nearby_sharing_get_intent", 2L, true);
        new Feature("nearby_sharing_get_share_targets", 1L, true);
        new Feature("nearby_sharing_sync", 2L, true);
        new Feature("nearby_sharing_get_actions", 5L, true);
        new Feature("nearby_sharing_suspend", 1L, true);
        new Feature("nearby_sharing_unsuspend", 1L, true);
        new Feature("nearby_sharing_update_suspend_options", 1L, true);
        new Feature("nearby_sharing_register_attachments", 1L, true);
        new Feature("nearby_sharing_unregister_attachments", 1L, true);
        new Feature("nearby_sharing_opt_in_by_remote_copy", 1L, true);
        new Feature("nearby_sharing_get_opt_in_status", 1L, true);
        new Feature("nearby_sharing_qr_code", 2L, true);
        new Feature("nearby_sharing_qr_code_cloud_transfer", 1L, true);
        new Feature("nearby_sharing_reset", 1L, true);
        new Feature("nearby_sharing_get_downloads_directory", 1L, true);
        new Feature("nearby_sharing_set_downloads_directory", 1L, true);
        new Feature("nearby_sharing_state_observer", 1L, true);
        new Feature("nearby_sharing_contacts_upload_consent", 1L, true);
        new Feature("feature_nearby_sharing_install_update", 1L, true);
        new Feature("nearby_sharing_validate_pin", 1L, true);
        new Feature("nearby_sharing_get_temporary_contacts", 1L, true);
        new Feature("nearby_sharing_revoke_temporary_contact", 1L, true);
        new Feature("nearby_sharing_set_providers_enabled", 1L, true);
        new Feature("nearby_sharing_is_provider_enabled", 1L, true);
        new Feature("nearby_uwb_subscribe_to_uwb_availability", 1L, false);
        new Feature("nearby_uwb_unsubscribe_from_uwb_availability", 1L, false);
    }
}
